# Tomcat
server:
  port: 20000

# 数据库支持 mysql postgresql
gen:
  author: lucky_fd
  database-type: mysql # 支持mysql、postgresql。选择数据库类型后，还需要配置相应数据库的数据源


# mysql 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yushi-blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: 123456

# postgresql 数据源配置
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://127.0.0.1:5432/gen_code?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#    username: postgres
#    password: 123456

mybatis:
  typeAliasesPackage: com.yushi.code.domain
  mapperLocations: classpath:mapper/**/*.xml
  # mybatis日志输出
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 表自动生成参数配置
east:
  # 扫描生成表的包路径
  entity-package: com.yushi.code.entity
  # ddl执行策略：
  # none：不执行任何操作
  # create：每次执行创建操作，表存在则删除再创建
  # update：如果表不存在，则创建表；如果表存在，则更新表（已定义字段不会更新，避免数据库字段类型不一致冲突，只更新新加字段）
  ddl-auto: update